#!/bin/bash

#
# git extension:
# Create a tar-archive of the current repo in the parent directory
#

DATETIME=`date "+%Y%m%d_%H%M"`

ORIGDIR="${PWD##*/}"
REPODIR="${ORIGDIR// /_}"
PARENT=`dirname "$PWD"`

tar -C "$PARENT" -cf ../git_panic_${DATETIME}-${REPODIR}.tar "$ORIGDIR"
echo "Panicfile git_panic_${DATETIME}-${REPODIR}.tar stored in the parent (${PARENT})."
echo
